PickNikRobotics/generate_parameter_library

- CONTRIBUTING.md
- LICENSE
- example/CMakeLists.txt
- example/include/generate_parameter_library_example/validators.hpp
- example/package.xml
- example/src/main.cpp
- generate_parameter_library/CMakeLists.txt
- generate_parameter_library/cmake/generate_parameter_library.cmake
- generate_parameter_library/generate_parameter_library-extras.cmake
- generate_parameter_library/package.xml
- generate_parameter_library_py/generate_parameter_library_py/main.py
- generate_parameter_library_py/package.xml
- generate_parameter_library_py/setup.py
- generate_parameter_library_py/test/test_copyright.py
Signed-off-by: Tyler Weaver <maybe@tylerjw.dev>
> License with tests

- generate_parameter_library_py/generate_parameter_library_py/main.py
- generate_parameter_library_py/generate_parameter_library_py/templates/template.txt
Signed-off-by: Tyler Weaver <maybe@tylerjw.dev>
> Optional arguments for validation

- generate_parameter_library/cmake/generate_parameter_library.cmake
> Fix optional header

- README.md
- generate_parameter_library/cmake/generate_parameter_library.cmake
- generate_parameter_library/generate_parameter_library-extras.cmake
- generate_parameter_library/package.xml
- generate_parameter_library_py/generate_parameter_library_py/cpp_templates/validators.hpp
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/parameter_listener
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/parameter_validation
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/update_parameter
- generate_parameter_library_py/generate_parameter_library_py/main.py
> fmt for formatting errors

- generate_parameter_library_py/generate_parameter_library_py/cpp_templates/validators.hpp
- generate_parameter_library_py/generate_parameter_library_py/main.py
> Fix exception error message

- example/src/parameters.yaml
- generate_parameter_library_py/generate_parameter_library_py/cpp_templates/validators.hpp
- generate_parameter_library_py/generate_parameter_library_py/main.py
> Add bounds validators

- .github/workflows/ci.yaml
- generate_parameter_library_py/package.xml
- generate_parameter_library_py/setup.py
> Depend on typeguard through rosdep

- README.md
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/parameter_listener
- generate_parameter_library_py/generate_parameter_library_py/validators/validators.hpp
> Validate strings and arrays for size

- README.md
Signed-off-by: Tyler Weaver <tylerjw@gmail.com>
Fixes #35
> README.md updates for parameter_validators lib

- generate_parameter_library/cmake/generate_parameter_library.cmake
Signed-off-by: Tyler Weaver <tylerjw@gmail.com>
Tiny PR to reuse a variable to clean-up some paths in the cmake.
> Cleaup cmake paths

- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/parameter_library_header
> Lock mutex around modifying internal state of ParamListener

- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/declare_parameter
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/declare_runtime_parameter
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/parameter_library_header
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/remove_runtime_parameter
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/set_parameter
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/update_parameter
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/update_runtime_parameter
> Parameter prefix

- README.md
- example/CMakeLists.txt
- example/src/parameters.yaml
- example/test/example_params.yaml
- example/test/example_test_gmock.cpp
- example/test/example_test_gtest.cpp
- generate_parameter_library/cmake/generate_parameter_library.cmake
- tcb_span/include/tcb_span/span.hpp
- Add macros for executing tests with provided yaml files.
- Add documentation into readme.
> 🚀 Add cmake macros for using tests with example yaml files. 🤖

- example/README.md
The readme for the exmaple is out of date. This updates it to the latest state of output from the various commands.
> Update README for example

- generate_parameter_library/CMakeLists.txt
- parameter_traits/CMakeLists.txt
> Drop requirement for CMake to 3.16

- generate_parameter_library_py/package.xml
This should fix an issue showing up in the CI for MoveIt @Abishalini
> Depend on python dependencies in package.xml

- generate_parameter_library_py/generate_parameter_library_py/main.py
> Use typing syntax which is compatible with Python 3.6

- example/CMakeLists.txt
- generate_parameter_library/cmake/generate_parameter_library.cmake
- parameter_traits/CMakeLists.txt
https://colcon.readthedocs.io/en/released/user/overriding-packages.html#how-to-make-it-easier-for-your-users-to-override
> Make it easy for users to override

- generate_parameter_library_py/generate_parameter_library_py/test/YAML_parse_error_test.py
- generate_parameter_library_py/setup.py
> Fixed tests never failing although file not found

- generate_parameter_library_py/generate_parameter_library_py/generate_markdown.py
> Markdown: Fix output in current folder

- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/cpp/parameter_library_header
> Use node logger

- README.md
Adding some info about parameter maps.
> Add paragraph on mapped parameters

- generate_parameter_library_py/generate_parameter_library_py/python_convertions.py
- generate_parameter_library_py/generate_parameter_library_py/python_validators.py
Fixes for some minor bugs in the Python code generation:
- Fix unique() validator doing just the opposite (error on unique values) 1fefe54508b2cdcbc6c70e6f1db1e9b10585603e
- Fix the template for raising of InvalidParameterValueExceptions 31980b964943136777a9a5a26916375a9740d103
> Bugfixes on Python code generation

- .pre-commit-config.yaml
Updated psf black to last 23 version .
Lot ox fix.
Python 3.7 runtime support are removed.
[docker] Build with 3.12 image
> Update black lib into .pre-commit-config.yaml

- .pre-commit-config.yaml
Updated to last codespell version
> Update codespell lib into .pre-commit-config.yaml

- .pre-commit-config.yaml
Update black into  .pre-commit-config.yaml
fixs:
https://github.com/psf/black/releases
> Update black lib
