PickNikRobotics/generate_parameter_library

- generate_parameter_library/CMakeLists.txt
- generate_parameter_library/cmake/generate_parameter_library.cmake
- generate_parameter_library/package.xml
I've tested this with my current PR for forward_command_controller.
> Support exporting parameter libraries

- tcb_span/CMakeLists.txt
- tcb_span/package.xml
Signed-off-by: Tyler Weaver <maybe@tylerjw.dev>
Fixes error found on buildfarm. @jspricke thank you for looking at our logs and finding what was wrong.
https://build.ros2.org/job/Hbin_uJ64__tcb_span__ubuntu_jammy_amd64__binary/1/console
> Add test dependency

- README.md
- generate_parameter_library_py/setup.py
- parameter_traits/include/parameter_traits/validators.hpp
- parameter_traits/test/CMakeLists.txt
- parameter_traits/test/validators_tests.cpp
Fixes #59 
This PR clarifies which validators can be used for which types of parameters in the README, fixes the odd bugs that @destogl found with vectors of strings, and adds unit tests for all the validator functions.
> Test validators and fix bugs

- example/src/parameters.yaml
- generate_parameter_library_py/generate_parameter_library_py/main.py
Adding support to map parameters which have "_" in their name.
This also make the code more about explicit keywords and without assumption about name format.
Check the extended example parameter setup for more details.
> 🈵 Support use of '_' in mapped parameters.

- generate_parameter_library/cmake/generate_parameter_library.cmake
I don't know if anyone else had this issue, but although [the docs](https://design.ros2.org/articles/ros_command_line_arguments.html) states:
> Extraction
> Command line argument extraction happens within rcl. When an instance of the --ros-args flag is found in argv, until either a double dash token (--) is found or the end of the argument array is reached, all arguments that follow are taken as ROS specific arguments to be parsed as such. Remaining arguments can still be accessed by the user via rcl API.
I don't think the double dash of "--gtest_output=xml:${result_file}" counts. In my ros2_control fork using generate_parameter_library I get the following error without the trailing "--":
- joint_limits_rosparam_test
<<< failure message
-- run_test.py: invoking following command in …
> Added -- for ros-args to find

- parameter_traits/CMakeLists.txt
Without this, I get the following error when building a package:
```
CMake Error at CMakeLists.txt:33 (add_library):
Target "cool_position_controllers" links to target "tcb_span::tcb_span"
but the target was not found.  Perhaps a find_package() call is missing for
an IMPORTED target, or an ALIAS target is missing?
CMake Error at /opt/ros/rolling/share/ament_cmake_gmock/cmake/ament_add_gmock.cmake:69 (add_executable):
Target "test_position_controller_base" links to target "tcb_span::tcb_span"
but the target was not found.  Perhaps a find_package() call is missing for
an IMPORTED target, or an ALIAS target is missing?
Call Stack (most recent call first):
/opt/ros/rolling/share/ament_cmake_gmock/cmake/ament_add_gmock.cmake:52 (_ament_add_gmock)
CMakeLists.txt:93 (ament_add_gmock)
``` …
> Missing export os depency causes downstream packages to fail

- example/CMakeLists.txt
- generate_parameter_library/CMakeLists.txt
- generate_parameter_library/package.xml
- parameter_traits/CMakeLists.txt
- Remove superfluous call in cmake
- Buildtool export depend on python package
- Use package name instead of variable
- Standardize CMake in example
- parameter_traits HAS_LIBRARY_TARGE
Reference:
https://docs.ros.org/en/rolling/How-To-Guides/Ament-CMake-Documentation.html#building-a-library
> standardize cmake

- generate_parameter_library_py/generate_parameter_library_py/main.py
RHEL 8 packages PyYAML 3.12, which does not have the `FullLoader` referenced here. If the `SafeLoader` can't be used, the only other option available is the `Loader` (aka `UnsafeLoader`).
Fixes #85
> Use YAML loader which is compatible with PyYAML 3.12

- generate_parameter_library_py/package.xml
I'm sorry about the "onion peeling" here, but my local test environment wasn't sufficient to verify that dependencies were properly declared. It's very interesting that this missing dependency doesn't break the Ubuntu builds, but clearly it is indeed undeclared here.
Example failure:
https://build.ros2.org/job/Rbin_rhel_el864__generate_parameter_library_example__rhel_8_x86_64__binary/47
Referenced here:
https://github.com/PickNikRobotics/generate_parameter_library/blob/33caa0e83535db8cb7077e021b4d1b128bb41a24/generate_parameter_library_py/generate_parameter_library_py/main.py#L32
The rosdep key is here:
https://github.com/ros/rosdistro/blob/39f72ed2f2d83dba4cb1c71520dfd3c123b1ad0d/rosdep/python.yaml#L9746-L9759
> Add missing dependency on PyYAML

- generate_parameter_library/cmake/generate_parameter_library.cmake
On macOS, CMake (3.23) could not build the generated target: It cannot produce the static library with the error
```
ar: no archive members specified
```
because there is no object file supplied (the generated target is header-only). Simply adding the keyword `INTERFACE` disables building the static library.
> Add keyword INTERFACE to fix build error 'ar: no archive members specified' on macOS

- README.md
- example/src/parameters.yaml
- generate_parameter_library_py/generate_parameter_library_py/test/valid_parameters.yaml
For the reference: PickNikRobotics/RSL#78
Deprecation can be seen on the CI, e.g.:
https://github.com/ros-controls/ros2_controllers/actions/runs/4618180647/jobs/8165304008?pr=434#step:6:877
For an example of changes see ros-controls/ros2_controllers#561
> Mark deprecated rsl method and propose alternative in the docs.

- example/CMakeLists.txt
- example/src/parameters.yaml
- example/test/descriptor_test_gtest.cpp
- example/test/example_test_gtest.cpp
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/declare_parameter
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/declare_runtime_parameter
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/parameter_library_header
- generate_parameter_library_py/generate_parameter_library_py/main.py
- generate_parameter_library_py/generate_parameter_library_py/test/validation_only_parameters.yaml
This PR resolves [Issue 96](https://github.com/PickNikRobotics/generate_parameter_library/issues/96). 
This uses the `declare_parameter` and `declare_runtime_parameter` templates to populate the parameter descriptor. 
For this, some string checking on the validation function was added to see if it was appropriate to populate the Descriptor range constraints.  In the jinja templates I simply check against the string name of the validation function and the number of arguments. This should work in all cases here, but strange things may happen if another validation function with a substring of "gt" or "lt" with 1 argument, or "bounds" with 2 args is either created in RSL or in a user defined validation function. For this purpose I figure this is acceptable. 
This also may not allow setting of …
> Populate Range Constraints in Parameter Descriptors from Validation Functions

- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/declare_parameter
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/declare_runtime_parameter
- generate_parameter_library_py/generate_parameter_library_py/main.py
- generate_parameter_library_py/generate_parameter_library_py/test/validation_only_parameters.yaml
Due to the string checking in the declare(_runtime)_parameters templates, `size_lt` and `size_gt` would incorrectly populate the descriptor range constraints since it also has 1 argument. This changes that line in the template to explicitly check for `lt`, `lt_eq`, `gt`, and `gt_eq` so that we avoid this error and hopefully other errors in the future. 
Not the cleanest implementation, but added a function_base_name without the template brackets `<>`. This passes the checks I've looked for and should reduce the descriptors being inadvertently filled unless the validation function name has both the substring `lesser`/`greater` and `bounds` in it with 1 argument. Could clean up in future if desired but would need to think about how to structure this in the jinja templates / main.py, as it's …
> Fix Parameter Descriptor Incorrectly Populating Range Constraints for size_lt and size_gt

- README.md
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/parameter_library_header
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/set_parameter
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/set_runtime_parameter
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/update_parameter
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/update_runtime_parameter
Fixes #86
If you build this locally, you can test this by running the example node with debug logging:
```shell
ros2 run generate_parameter_library_example test_node --ros-args --params-file src/generate_parameter_library/example/config/implementation.yaml --log-level debug
```
Then in another terminal change a parameter:
```shell
ros2 param set /admittance_controller control.frame.id new_frame
```
You should see an output like this in the logs:
```
[DEBUG] [1681944620.098785049] [admittance_controller]: control.frame.id: string = new_frame
```
> Log when a parameter is set

- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/markdown/parameter_detail
A proposal for a markdown template without a table, closes #113 
Example from [this yaml ](https://github.com/ros-controls/ros2_controllers/blob/master/admittance_controller/src/admittance_controller_parameters.yaml)
> ## joint_damping 
> 
> Specifies the joint damping applied used in the admittance calculation.
> 
> * Type: `double`
> * Default Value: 5.0
> 
> 
> *Constraints:*
>  - greater than or equal to 0.0
> Update markdown template

- generate_parameter_library_py/generate_parameter_library_py/generate_markdown.py
Fix empty arguments case and add custom validator prompt, closes #112 
Example output from [this yaml](https://github.com/ros-controls/ros2_controllers/blob/master/joint_trajectory_controller/src/joint_trajectory_controller_parameters.yaml)
> *Constraints:*
>  - contains no duplicates
>  - every element is one of the list ['position', 'velocity', 'acceleration']
>  - custom validator: state_interface_type_combinations
> Fix empty arguments case and add custom validator prompt

- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/rst/default_config
Use the correct markup format in the code block.
> ReST: Use correct syntax highlighting

- generate_parameter_library_py/setup.py
I don't know exactly what happend, but two weeks ago `sudo python setup.py install` worked in our CI, but now it [doesn't](https://github.com/ros-controls/control.ros.org/actions/runs/5169706099/jobs/9312124488#step:7:82). 
So I [changed the installation](https://github.com/ros-controls/control.ros.org/pull/106) to  `python -m pip install .`, but it [complains for missing yaml module](https://github.com/ros-controls/control.ros.org/actions/runs/5170704614/jobs/9313777855#step:7:83). Adding it to `install_requires` fixed that for me.
> Add pyyaml as dependency

- generate_parameter_library_py/generate_parameter_library_py/cpp_convertions.py
Just found the library and I really like it. It saves so much time; thank you for your work. There is just a tiny error in the code generator, causing the following error
```
error: temporary of non-literal type ‘std::__cxx11::basic_string<char>’ in a constant expression
256 |           throw rclcpp::exceptions::InvalidParameterValueException(fmt::format("Invalid value set during initialization for parameter 'led_strip.block_length': " + validation_result.error()));
``` 
The fix is easy, replace the "+ validation_result" with ", validation_result" and add a "{}" for placeholding. That is all this PR does
> Fixed incorrect usage of fmt, causing compile errors

- README.md
The example for adding a custom validator function was labeled "Here is an example custom allocator."
I assume this is kind of a false friend, as the devs more often are confronted with custom allocators rather than validators ;-)
> Replace allocator with validator

- .github/workflows/ci.yaml
- README.md
- example/CMakeLists.txt
- example/include/generate_parameter_library_example/example_validators.hpp
- example/src/minimal_publisher.cpp
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/cpp/parameter_library_header
- generate_parameter_library_py/generate_parameter_library_py/test/validation_only_parameters.yaml
`lower_bounds` and `upper_bounds` are deprecated functions and replaced by `lt_eq` and `gt_eq` which do the same thing. This PR removes the documentation of the deprecated functions, they will be deleted in the future but for now there is a deprecation warning in RSL for them.
> Remove documentation of deprecated validator functions

- example_python/package.xml
The `setup.py` for the `generate_parameter_module_example` package fails to run when the `generate_parameter_library_py` package is not on the Python path. This PR should fix the issue by adding the dependency to  package.xml.
> add dependency to python example package

- example_python/setup.py
This PR adds a guard to the `generate_parameter_module ` call in the setup.py to make sure the code generation doesn't run when  `setup.py clean` is run.
> Prevent module import  when running `setup.py clean`

- example_python/README.md
I've gone over the provided examples and updated some paths and expected log messages.
I've also split the example/README.md into a C++ and a Python version.
> Fixed paths and expected log messages in example/README.md

- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/python/parameter_library_header
I have tested your great library for generating parameters for my Python node and noticed that the parameter `my_parameter` was always included. I presume this was accidental.
This PR removes the `my_parameter` from the `parameter_library_header` template.
> Remove `my_parameter` from python template

- generate_parameter_library_py/generate_parameter_library_py/parse_yaml.py
For typeguard==3.0.2, `default_value: any` raised a `TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union` during colcon build of a Python node using this library. Using the `Any` from the `typing` module fixed this issue.
Yes, this problem does not occur with the typeguard version provided by apt (2.2.2), but could also occur if Ubuntu bumps that version or for other users with a newer local pip install of typeguard.
> Fix typeguard error

- generate_parameter_library_py/generate_parameter_library_py/generate_markdown.py
Fixes a simple typo for the markdown validator replacement texts.
> Markdown: Fix sentence for size_lt

- generate_parameter_library_py/generate_parameter_library_py/parse_yaml.py
Hi!
I have been using your library for a while and it's really great!
I have a very particular issue that is probably very niche, but I decided to try and fix it. As you can see in the pull request, the fix is very simple.
My use case is very particular, I use docker to prebuild my workspace and then I hop into the container to develop. When prebuilding with `--symlink-install`, this package create the module inside my `src/` directory. 
The problem arise when I mount my workspace inside the container. It essentially wipe the generated modules. The solution I use is to rebuild the packages inside my container and then commit the generated modules.
Which comes to the main point of this pull request, the trailing new line. Since most linter and formatter enforce a newline at the end of a …
> parse_yaml.py: keep the trailing newline

- generate_parameter_library_py/generate_parameter_library_py/generate_markdown.py
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/cpp/declare_parameter
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/cpp/declare_runtime_parameter
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/markdown/parameter_detail
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/rst/parameter_detail
- generate_parameter_library_py/generate_parameter_library_py/parse_yaml.py
- generate_parameter_library_py/generate_parameter_library_py/string_filters_cpp.py
- generate_parameter_library_py/generate_parameter_library_py/test/YAML_parse_error_test.py
This closes #118 and closes #126.
I had to write a custom jinja2 filter `valid_string_cpp` to create valid c++ string literals for multi-line descriptions.
This also adds rudimentary support for the default config:
```yaml
joint_trajectory_controller:
ros__parameters:
action_monitor_rate: 20.0
allow_integration_in_goal_trajectories: false
allow_nonzero_velocity_at_trajectory_end: false
allow_partial_joints_goal: false
cmd_timeout: 0.0
command_interfaces: '{}'
command_joints: '{}'
constraints:
<joints>:
goal: 0.0
trajectory: 0.0
goal_time: 0.0
stopped_velocity_tolerance: 0.01
gains:
<joints>:
angle_wraparound: false
d: 0.0
ff_velocity_scale: 0.0
i: 0.0
i_clamp: 0.0
p: 0.0
interpolation_method: splines
joints: '{}'
open_loop_control: false
state_interfaces: '{}'
```
Would there be any …
> markdown/rst: Support __map_ and nested parameters

- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/python/declare_struct
A description of a bug with Python runtime parameters is detailed here https://github.com/PickNikRobotics/generate_parameter_library/issues/163. This PR fixes the issue by preventing default initialized value from being created every time a parameter is accessed.
> Fix Python runtime parameters bug

- generate_parameter_library/CMakeLists.txt
With #171 I realized that this library has a wrong `cmake_minimum_required` declaration, `cmake_path` is available only from 3.20 on:
https://cmake.org/cmake/help/latest/command/cmake_path.html
> Update `cmake_minimum_required` to 3.20

- example/src/parameters.yaml
- example_python/generate_parameter_module_example/parameters.yaml
- generate_parameter_library_py/generate_parameter_library_py/generate_python_module.py
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/python/declare_parameter
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/python/declare_runtime_parameter
- generate_parameter_library_py/generate_parameter_library_py/parse_yaml.py
- generate_parameter_library_py/generate_parameter_library_py/string_filters_cpp.py
Newlines were breaking the code generation for Python https://github.com/PickNikRobotics/generate_parameter_library/issues/170. This PR fixes the issue and reformats the C++ to print better with `ros2 param describe...` The following out shows the new format.
```
Parameter name: hover_override
Type: integer
Description: Override hover action:
0: Hover
1: Push
2: Pull
-1: Do not override
Constraints:
```
The old format was like this 
```
Parameter name: hover_override
Type: integer
Description: Override hover action: 0: Hover 1: Push 2: Pull -1: Do not override
Constraints:
```
> Fix newline issue

- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/python/parameter_library_header
This PR address this issue https://github.com/PickNikRobotics/generate_parameter_library/issues/174
> Add # `flake8: noqa` to Python module template

- generate_parameter_library/cmake/generate_parameter_library.cmake
This PR uses the `python_install_dir` macro to fix the install path of Python when using iron. Addresses https://github.com/PickNikRobotics/generate_parameter_library/issues/175
> Use `python_install_dir` to set Python install path

- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/cpp/parameter_library_header
When looking at generated code, I noticed there was a member function generated named `update_interal_params` which should be `update_internal_params`.
> Fix typo in `update_interal_params`

- README.md
- example/src/parameters.yaml
- example_cmake_python/cmake_generate_parameter_module_example/parameters.yaml
- example_python/generate_parameter_module_example/parameters.yaml
- generate_parameter_library_py/generate_parameter_library_py/test/invalid_syntax.yaml
- generate_parameter_library_py/generate_parameter_library_py/test/missing_type.yaml
- generate_parameter_library_py/generate_parameter_library_py/test/valid_parameters.yaml
- generate_parameter_library_py/generate_parameter_library_py/test/valid_parameters_with_none_type.yaml
- generate_parameter_library_py/generate_parameter_library_py/test/validation_only_parameters.yaml
- generate_parameter_library_py/generate_parameter_library_py/test/wrong_default_type.yaml
I noticed in some reviews internally that the brackets were used inconsistently. Turns out they were mostly copy pasted from the great parameter library.
May I suggest dropping the bracket syntax? It's yaml after-all, not json :slightly_smiling_face: 
As you can already see in the first README example, it was a bit inconsistent, they are not used after `turtlesim` but are used after `background`.
> Drop yaml brackets for consistency and readability

- example/test/example_test_gtest.cpp
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/cpp/parameter_library_header
This pull request adds a new function, `try_get_params()`, to improve responsiveness especially in real-time systems by avoiding blocking operations. The existing `is_old()` function also risks blocking, so I incorporated it into `try_get_params()`.
> Add Non-Blocking try_get_params Function for Real-Time Control Systems

- generate_parameter_library_py/generate_parameter_library_py/generate_python_module.py
This was a tricky one to track down, as it happened extremely rarely.
The case is, you've got two different Python parameter modules you're generating within a single CMake project
```
generate_parameter_module(first_generated_params
${PROJECT_NAME}/first_params.yaml
)
generate_parameter_module(second_generated_params
${PROJECT_NAME}/second_params.yaml
)
```
When `make` finally is autorun by `colcon build`, it's done with parallelization and the two commands can actually be run simultaneously. When this happened (and it was rare but not as uncommon as I would have thought, definitely not reliably reproducible but would fail CI runs sporadically) it looks like this:
```
Running generate_parameter_library_py/generate_parameter_library_py/generate_python_module.py …
```
> Use exist_ok=True in makedirs instead of checking for existence

- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/python/parameter_library_header
This PR makes it so the `parameter_listener` can refresh it's copy of parameters with ones specified in a yaml dictionary and would close #208.
To load and the get the parameters
```python
self.param_listener = my_param_namespace.ParamListener(self.node)
path_to_config = os.path.dirname(__file__) + '/config/my_config_file.yaml'
with open(path_to_config) as file:
configParamsFromYaml = yaml.safe_load(file)['my_param_namespace']['ros__parameters']
self.param_listener.set_params_from_dict(configParamsFromYaml)
self.test_params = self.param_listener.get_params()
```
> Add ability for param_listener to load values from yaml dictionary

- .github/workflows/ci.yaml
- generate_parameter_library_py/generate_parameter_library_py/cpp_convertions.py
- generate_parameter_library_py/generate_parameter_library_py/parse_yaml.py
- generate_parameter_library_py/generate_parameter_library_py/python_convertions.py
- generate_parameter_library_py/generate_parameter_library_py/test/YAML_parse_error_test.py
It appears that the CI for rolling might be running Python with optimization. This disables type checks causing a test to fail. This PR disables the test if the environment is set to optimize.
> Fix test on rolling CI

- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/python/update_runtime_parameter
When calling `param_listener.update(override_parameters)` nested parameters will fail to load because of the missing namespace separator `.`
This PR fixes the template that creates update() function for the parameters with mapped namespaces so that they match & update properly.
> Fix nested parameter update

- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/cpp/declare_parameter
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/cpp/declare_runtime_parameter
As you can see the cpp templates are setting the `to_value` twice instead of the `from_value`. Probably a typo.
This leads to a wrong floating point range in the parameter descriptor.
> Fix floating point range for upper/lt/lt_eq validations

- example/test/descriptor_test_gtest.cpp
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/cpp/declare_parameter
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/cpp/declare_runtime_parameter
Hi everyone,
This PR fixes #199. Since ROS uses int64_t to store integer parameters, int64_t numeric limits should be used instead of int.
i simply corrected the template files and the associated unit tests.
Any thoughts ?
> Fix a typo preventing to use the full int64_t range when using gt<> and lt<> validators

- generate_parameter_library/cmake/generate_parameter_library.cmake
The variable `generate_parameter_library_cpp_BIN` was cached, which caused build issues when switching between binary and source installed versions. This prevents the error `/opt/ros/humble/bin/generate_parameter_library_cpp: No such file or directory`.
`
> Disable cache for `generate_parameter_library_cpp_BIN`

- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/python/parameter_library_header
> fix error with not being able to find unpack_parameter_dict when using set_params_from_dict

- .github/workflows/ci.yaml
There is an issue when CI fails, in that both the test and log results artifacts uploaded on failure had the same name!
```
Run actions/upload-artifact@v4
With the provided path, there will be [12](https://github.com/PickNikRobotics/generate_parameter_library/actions/runs/12634499926/job/35202363937#step:5:13)2 files uploaded
Artifact name is valid!
Root directory input is valid!
Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run
```
> Use unique artifact name to upload logs on CI failure

- generate_parameter_library_py/generate_parameter_library_py/setup_helper.py
The Python library install path is incorrect and writes the generated files to an incorrect location.
The path has an additional `pkg_name` folder in the target directory.
Tested on Humble (Ubuntu 22)
> Fix python lib install path

- README.md
Currently an example of accessing mapped parameters is misleading. This PR aims to propose an update showcasing the exact syntax.
> Update accessing mapped parameters in README

- generate_parameter_library_py/generate_parameter_library_py/cpp_conversions.py
- generate_parameter_library_py/generate_parameter_library_py/parse_yaml.py
- generate_parameter_library_py/generate_parameter_library_py/python_conversions.py
- generate_parameter_library_py/generate_parameter_library_py/setup_helper.py
Saw some typos so I wanted to fix them.
> Fix conversion typos

- generate_parameter_library_py/generate_parameter_library_py/setup_helper.py
This reverts commit 4e92cc4e9da5e7a853ac0b1762db85e1f859d91b.
Turns out I took #207 in good faith, but it does cause problems.
Without that PR, this is what a custom module named `admittance_params.py` installs into. This is correct:
With that PR, it goes to the wrong folder one level up:
> Revert "Fix python lib install path (#207)"

- generate_parameter_library_py/generate_parameter_library_py/setup_helper.py
Existing install of the parameter python script fails when using `colcon build` with `--merge-install` and/or `--install-base /opt/someuser/ros_ws`
This PR enables us to pass through a custom install base e.g. `/opt/someuser/ros_ws` as well as the merge-install flag for proper installation of python packages in the same way as `colcon build`.
One way to obtain the merge install path can be done as below and passed into `generate_parameter_module`. 
```
if len(sys.argv) >= 2 and sys.argv[1] != 'clean':
from generate_parameter_library_py.setup_helper import generate_parameter_module
colcon_prefix_path = os.getenv("COLCON_PREFIX_PATH", None)
if not colcon_prefix_path:
raise ValueError(f"Unable to find merge install base")    
base_dir = colcon_prefix_path.split(':')[0] …
```
> fix: merge install for python packages

- README.md
- example/include/generate_parameter_library_example/minimal_publisher.hpp
- example/src/minimal_publisher.cpp
- generate_parameter_library_py/generate_parameter_library_py/jinja_templates/cpp/parameter_library_header
Hi,
I added functionality to bind a custom callback. This callback will be fired when the parameters are updated, and those updated parameters are then directly available. I think this covers https://github.com/PickNikRobotics/generate_parameter_library/issues/6
> Feat: add user callback
